name: Run Tests

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.4.1' 
    - name: setup
      run: |
        gem install bundler
        bundle install
    - name: test
      run: rake
